# device/samsung/gtelwifi/BoardConfig.mk

# Platform info
TARGET_BOARD_PLATFORM := sc8830
BOARD_VENDOR := samsung
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8

# CPU / ABI
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

# Partition sizes
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1650612736
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_CACHEIMAGE_PARTITION_SIZE := 134217728
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
# Kernel
BOARD_KERNEL_IMAGE_NAME := zImage
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=gtelwifi
BOARD_KERNEL_HEADERS := prebuilts/kernel-headers
TARGET_KERNEL_CONFIG := cyanogen_vivalto3mve_defconfig
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

TARGET_USES_QCOM_BSP := true
TARGET_USES_QCOM_DISPLAY := true
TARGET_USES_QCOM_HARDWARE := true
TARGET_USES_QCOM_MEDIA := true

# Bootanimation
TARGET_SCREEN_HEIGHT := 1280
TARGET_SCREEN_WIDTH := 800

GENERATE_OTAPACKAGE := true
WITH_DEXPREOPT := false
WITH_DEXPREOPT_BOOT_IMG_AND_SYSTEM_SERVER_ONLY := false
SELINUX_IGNORE_NEVERALLOWS := true
TARGET_LDFLAGS += -Wl,--allow-multiple-definition
WITH_DEXPREOPT := false
DONT_DEXPREOPT_PREBUILTS := true
